/**
 * ══════════════════════════════════════════════════════════════════════════
 * 🔱 ANTIGRAVITY CLOUD GITHUB AUTO-CREATOR & DEPLOYER
 * ══════════════════════════════════════════════════════════════════════════
 * Automatically creates brand-new GitHub repositories and pushes generated
 * full-stack applications directly to GitHub from anywhere (Phone / Cloud / PC)!
 * ══════════════════════════════════════════════════════════════════════════
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..');

const GITHUB_CONFIG_PATH = path.join(rootDir, 'config', 'github_config.json');

export function getGitHubConfig() {
  if (fs.existsSync(GITHUB_CONFIG_PATH)) {
    try {
      return JSON.parse(fs.readFileSync(GITHUB_CONFIG_PATH, 'utf8'));
    } catch (e) {}
  }
  return {
    githubToken: '',
    githubUsername: '',
    defaultVisibility: 'public',
    enabled: false
  };
}

export function saveGitHubConfig(cfg) {
  const cur = getGitHubConfig();
  const merged = { ...cur, ...cfg };
  fs.writeFileSync(GITHUB_CONFIG_PATH, JSON.stringify(merged, null, 2));
  return merged;
}


/**
 * Fetches the authenticated user's GitHub username from token

 * @param {string} token GitHub Personal Access Token
 * @returns {Promise<{success: boolean, username?: string, error?: string}>}
 */
export async function fetchGitHubUser(token) {
  try {
    const res = await fetch('https://api.github.com/user', {
      headers: {
        'Authorization': `token ${token.trim()}`,
        'Accept': 'application/vnd.github.v3+json',
        'User-Agent': 'Antigravity-Agent'
      }
    });
    const data = await res.json();
    if (res.ok && data.login) {
      return { success: true, username: data.login, name: data.name || data.login };
    }
    return { success: false, error: data.message || 'Invalid Token' };
  } catch (err) {
    return { success: false, error: err.message };
  }
}


/**
 * Creates a brand new GitHub Repository and commits all generated files
 * @param {string} repoName Name of repository to create
 * @param {string} description Repository description
 * @param {Array<{filename: string, content: string}>} files Code files to commit
 * @returns {Promise<object>}
 */
export async function createGitHubRepoAndPush(repoName, description, files = []) {
  const config = getGitHubConfig();
  if (!config.githubToken) {
    return {
      success: false,
      message: 'GitHub Token not configured. Please save your GitHub Personal Access Token.'
    };
  }

  const cleanRepoName = repoName.toLowerCase().replace(/[^a-z0-9_-]/g, '-').substring(0, 50);

  // 1. Create Repository via GitHub REST API
  try {
    const createRes = await fetch('https://api.github.com/user/repos', {
      method: 'POST',
      headers: {
        'Authorization': `token ${config.githubToken}`,
        'Accept': 'application/vnd.github.v3+json',
        'User-Agent': 'Antigravity-Agent'
      },
      body: JSON.stringify({
        name: cleanRepoName,
        description: description || 'Generated autonomously by Antigravity AI Agent',
        private: config.defaultVisibility === 'private',
        auto_init: true
      })
    });

    const repoData = await createRes.json();
    if (!createRes.ok && createRes.status !== 422) { // 422 = already exists
      return { success: false, error: repoData.message };
    }

    const repoUrl = repoData.html_url || `https://github.com/${config.githubUsername}/${cleanRepoName}`;

    // 2. Commit each file to the GitHub repository
    for (const f of files) {
      const contentEncoded = Buffer.from(f.content).toString('base64');
      const fileUrl = `https://api.github.com/repos/${config.githubUsername || repoData.owner.login}/${cleanRepoName}/contents/${f.filename}`;

      await fetch(fileUrl, {
        method: 'PUT',
        headers: {
          'Authorization': `token ${config.githubToken}`,
          'Accept': 'application/vnd.github.v3+json',
          'User-Agent': 'Antigravity-Agent'
        },
        body: JSON.stringify({
          message: `Add ${f.filename} (Autonomously generated by Antigravity)`,
          content: contentEncoded
        })
      });
    }

    return {
      success: true,
      repoUrl,
      repoName: cleanRepoName,
      filesPushed: files.length
    };
  } catch (err) {
    return { success: false, error: err.message };
  }
}
