/**
 * ══════════════════════════════════════════════════════════════════════════
 * 🔱 APEX-OMNIVERSE SOVEREIGN TITAN v12.5 — COMPLETE NIFTY 500 UNIVERSE
 * ══════════════════════════════════════════════════════════════════════════
 * 500 Authentic NSE equities covering:
 * • NIFTY 50, NIFTY NEXT 50, NIFTY MIDCAP 150, NIFTY SMALLCAP 250, SENSEX 30
 * ══════════════════════════════════════════════════════════════════════════
 */

export const NIFTY_500_UNIVERSE = [
  // ─── 1 to 100: MEGA-CAP & LARGE-CAP TITANS ───
  'RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'ICICIBANK.NS', 'BHARTIARTL.NS',
  'INFY.NS', 'ITC.NS', 'HINDUNILVR.NS', 'LT.NS', 'SBIN.NS',
  'BAJFINANCE.NS', 'HCLTECH.NS', 'MARUTI.NS', 'SUNPHARMA.NS', 'ADANIENT.NS',
  'KOTAKBANK.NS', 'TATAMOTORS.NS', 'AXISBANK.NS', 'NTPC.NS', 'TITAN.NS',
  'ONGC.NS', 'POWERGRID.NS', 'ADANIPORTS.NS', 'M&M.NS', 'ULTRACEMCO.NS',
  'BAJAJFINSV.NS', 'COALINDIA.NS', 'TATASTEEL.NS', 'ASIANPAINT.NS', 'JSWSTEEL.NS',
  'NESTLEIND.NS', 'SIEMENS.NS', 'GRASIM.NS', 'WIPRO.NS', 'IOC.NS',
  'VEDL.NS', 'ZOMATO.NS', 'DLF.NS', 'BEL.NS', 'HAL.NS',
  'TECHM.NS', 'VBL.NS', 'HINDALCO.NS', 'INDUSINDBK.NS', 'CIPLA.NS',
  'DRREDDY.NS', 'BPCL.NS', 'BRITANNIA.NS', 'TATACONSUM.NS', 'EICHERMOT.NS',
  'APOLLOHOSP.NS', 'DIVISLAB.NS', 'BAJAJ-AUTO.NS', 'HEROMOTOCO.NS', 'SBILIFE.NS',
  'HDFCLIFE.NS', 'LTIM.NS', 'SHRIRAMFIN.NS', 'PIDILITIND.NS', 'HAVELLS.NS',
  'GODREJCP.NS', 'DABUR.NS', 'MARICO.NS', 'BERGEPAINT.NS', 'COLPAL.NS',
  'MCDOWELL-N.NS', 'TRENT.NS', 'DIXON.NS', 'CDSL.NS', 'POLYCAB.NS',
  'ASTRAL.NS', 'DEEPAKNTR.NS', 'ATUL.NS', 'PIIND.NS', 'PERSISTENT.NS',
  'COFORGE.NS', 'MPHASIS.NS', 'VOLTAS.NS', 'CROMPTON.NS', 'KAYNES.NS',
  'ZENTEC.NS', 'BIOCON.NS', 'ZYDUSLIFE.NS', 'TORNTPHARM.NS', 'AUROPHARMA.NS',
  'IPCALAB.NS', 'ALKEM.NS', 'MUTHOOTFIN.NS', 'MAXHEALTH.NS', 'FORTIS.NS',
  'GODREJPROP.NS', 'OBEROIRLTY.NS', 'PHOENIXLTD.NS', 'PRESTIGE.NS', 'BHEL.NS',
  'ABB.NS', 'CUMMINSIND.NS', 'THERMAX.NS', 'TATAPOWER.NS', 'NHPC.NS',

  // ─── 101 to 200: MIDCAP 150 BLUECHIPS & MOMENTUM LEADERS ───
  'IRFC.NS', 'PFC.NS', 'RECLTD.NS', 'SUZLON.NS', 'IDEA.NS',
  'IDFCFIRSTB.NS', 'PNB.NS', 'BANKBARODA.NS', 'CANBK.NS', 'UNIONBANK.NS',
  'INDIANB.NS', 'IOB.NS', 'UCOBANK.NS', 'MAHABANK.NS', 'CENTRALBK.NS',
  'FEDERALBNK.NS', 'BANDHANBNK.NS', 'AUBANK.NS', 'LODHA.NS', 'MOTHERSON.NS',
  'BOSCHLTD.NS', 'MRF.NS', 'BALKRISIND.NS', 'APOLLOTYRE.NS', 'CEATLTD.NS',
  'EXIDEIND.NS', 'AMARAJABAT.NS', 'ENDURANCE.NS', 'SONACOMS.NS', 'UNOMINDA.NS',
  'TIINDIA.NS', 'BHARATFORG.NS', 'ABCAPITAL.NS', 'ABFRL.NS', 'ACC.NS',
  'ADANIENSOL.NS', 'ADANIGREEN.NS', 'ADANIPOWER.NS', 'ADANIWILMAR.NS', 'AEGISLOG.NS',
  'AIAENG.NS', 'AJANTPHARM.NS', 'ALKYLAMINE.NS', 'AMBUJACEM.NS', 'ANGELONE.NS',
  'APARINDS.NS', 'APLAPOLLO.NS', 'APTUS.NS', 'ASAHIINDIA.NS', 'ASHOKLEY.NS',
  'ASTERDM.NS', 'AVANTIFEED.NS', 'BALRAMCHIN.NS', 'BATAINDIA.NS', 'BAYERCROP.NS',
  'BDL.NS', 'BECTORFOOD.NS', 'BEML.NS', 'BIRLACORPN.NS', 'BLS.NS',
  'BLUEDART.NS', 'BLUESTARCO.NS', 'BSE.NS', 'BSOFT.NS', 'CAMPUS.NS',
  'CANFINHOME.NS', 'CAPL.NS', 'CARBORUNIV.NS', 'CASTROLIND.NS', 'CCL.NS',
  'CENTURYPLY.NS', 'CENTURYTEX.NS', 'CESC.NS', 'CGPOWER.NS', 'CHAMBLFERT.NS',
  'CHEMPLASTS.NS', 'CHOLAHLDNG.NS', 'CLEAN.NS', 'COCHINSHIP.NS', 'CONCOR.NS',
  'COROMANDEL.NS', 'CREDITACC.NS', 'CRISIL.NS', 'CYIENT.NS', 'DALBHARAT.NS',
  'DATAPATTNS.NS', 'DEEPAKFERT.NS', 'DELHIVERY.NS', 'DEVYANI.NS', 'EIDPARRY.NS',
  'EIHOTEL.NS', 'ELGIEQUIP.NS', 'EMAMILTD.NS', 'EMCURE.NS', 'ENGINERSIN.NS',
  'EQUITASBNK.NS', 'ERIS.NS', 'ESCORTS.NS', 'FDC.NS', 'FINCABLES.NS',

  // ─── 201 to 300: PHARMA, CHEMICALS & ENGINEERING GIANTS ───
  'FINEORG.NS', 'FINPIPE.NS', 'FIRSTCRY.NS', 'FLUOROCHEM.NS', 'GAIL.NS',
  'GICRE.NS', 'GLAND.NS', 'GLAXO.NS', 'GLENMARK.NS', 'GLS.NS',
  'GMDCLTD.NS', 'GNFC.NS', 'GODFRYPHLP.NS', 'GODREJIND.NS', 'GPIL.NS',
  'GRANULES.NS', 'GRAPHITE.NS', 'GRINDWELL.NS', 'GSFC.NS', 'GSPL.NS',
  'GUJGASLTD.NS', 'HEG.NS', 'HINDCOPPER.NS', 'HINDPETRO.NS', 'HINDZINC.NS',
  'HONAUT.NS', 'HUDCO.NS', 'IDBI.NS', 'IGL.NS', 'IIFL.NS',
  'INDHOTEL.NS', 'INDIACEM.NS', 'INDIAMART.NS', 'INDIGO.NS', 'INDUSTOWER.NS',
  'INFIBEAM.NS', 'INOXWIND.NS', 'INTELLECT.NS', 'IRB.NS', 'IRCON.NS',
  'ISEC.NS', 'ITI.NS', 'J&KBANK.NS', 'JBCHEPHARM.NS', 'JBMA.NS',
  'JINDALSAW.NS', 'JINDALSTEL.NS', 'JIOFIN.NS', 'JKCEMENT.NS', 'JKPAPER.NS',
  'JSL.NS', 'JSWENERGY.NS', 'JSWINFRA.NS', 'JUBLFOOD.NS', 'JUBLINGREA.NS',
  'JUBLPHARMA.NS', 'JWL.NS', 'JYOTHYLAB.NS', 'KAJARIACER.NS', 'KALPATPOWR.NS',
  'KALYANKJIL.NS', 'KANSAINER.NS', 'KARURVYSYA.NS', 'KEC.NS', 'KEI.NS',
  'KFINTECH.NS', 'KIRLOSENG.NS', 'KNRCON.NS', 'KPITTECH.NS', 'KPRMILL.NS',
  'KRBL.NS', 'KSB.NS', 'L&TFH.NS', 'LALPATHLAB.NS', 'LAURUSLABS.NS',
  'LEMONTREE.NS', 'LICHSGFIN.NS', 'LICI.NS', 'LLOYDSME.NS', 'LUPIN.NS',
  'LUXIND.NS', 'M&MFIN.NS', 'MAHINDCIE.NS', 'MAHLIFE.NS', 'MANAPPURAM.NS',
  'MAPMYINDIA.NS', 'MASTEK.NS', 'MAXESTATES.NS', 'MAZDOCK.NS', 'MEDANTA.NS',
  'METROPOLIS.NS', 'MFSL.NS', 'MGL.NS', 'MOTILALOFS.NS', 'MSUMI.NS',
  'NAM-INDIA.NS', 'NATCOPHARM.NS', 'NATIONALUM.NS', 'NAVINFLUOR.NS', 'NBCC.NS',

  // ─── 301 to 400: CONSUMER, DEFENSE, TECH & LOGISTICS ───
  'NCC.NS', 'NETWORK18.NS', 'NLCINDIA.NS', 'NOCIL.NS', 'NUVAMA.NS',
  'NYKAA.NS', 'OIL.NS', 'OLECTRA.NS', 'PAGEIND.NS', 'PATANJALI.NS',
  'PAYTM.NS', 'PFIZER.NS', 'PNBHOUSING.NS', 'PNCINFRA.NS', 'POONAWALLA.NS',
  'PRAKASH.NS', 'PVRINOX.NS', 'QUESS.NS', 'RADICO.NS', 'RAILTEL.NS',
  'RAINBOW.NS', 'RAMCOCEM.NS', 'RATNAMANI.NS', 'RAYMOND.NS', 'RBLBANK.NS',
  'RCF.NS', 'REDINGTON.NS', 'RELAXO.NS', 'RITES.NS', 'RKFORGE.NS',
  'ROUTE.NS', 'RRKABEL.NS', 'RPOWER.NS', 'RUSTOMJEE.NS', 'SAFARI.NS',
  'SAIL.NS', 'SANOFI.NS', 'SAPPHIRE.NS', 'SARDAEN.NS', 'SBICARD.NS',
  'SCHAEFFLER.NS', 'SCHNEIDER.NS', 'SHOPERSTOP.NS', 'SHREECEM.NS', 'SIGNATURE.NS',
  'SKFINDIA.NS', 'SOBHA.NS', 'SOLARINDS.NS', 'STARHEALTH.NS', 'SUMICHEM.NS',
  'SUNDARMFIN.NS', 'SUNDRMFAST.NS', 'SUNTECK.NS', 'SUPRAJIT.NS', 'SUPREMEIND.NS',
  'SUVENPHAR.NS', 'SWANENERGY.NS', 'SYMPHONY.NS', 'SYNGENE.NS', 'TANLA.NS',
  'TATACHEM.NS', 'TATACOMM.NS', 'TATAELXSI.NS', 'TATAINVEST.NS', 'TATATECH.NS',
  'TEAMLEASE.NS', 'TEJASNET.NS', 'TIMKEN.NS', 'TITAGARH.NS', 'TNPETRO.NS',
  'TORNTPOWER.NS', 'TRIDENT.NS', 'TRITURBINE.NS', 'TRIVENI.NS', 'TTML.NS',
  'TV18BRDCST.NS', 'TVSMOTOR.NS', 'UBL.NS', 'UJJIVANSFB.NS', 'USAMAMTR.NS',
  'UTIAMC.NS', 'VAIBHAVGBL.NS', 'VARROC.NS', 'VGUARD.NS', 'VIJAYA.NS',
  'VINATIORGA.NS', 'VIPIND.NS', 'VTL.NS', 'WELCORP.NS', 'WELSPUNLIV.NS',
  'WHIRLPOOL.NS', 'WOCKPHARMA.NS', 'ZENSARTECH.NS', 'ZYDUSWELL.NS', 'AARTIIND.NS',

  // ─── 401 to 500: HIGH-KINETIC SMALLCAP & SPECIALTY LEADERS ───
  'AAVAS.NS', 'ACE.NS', 'ADVENZYMES.NS', 'AGI.NS', 'AJMERA.NS',
  'AKZOINDIA.NS', 'ALLCARGO.NS', 'ALOKINDS.NS', 'AMBER.NS', 'ANANTRAJ.NS',
  'ANURAS.NS', 'APCOTEXIND.NS', 'ARCHIDPLY.NS', 'ARVINDFASN.NS', 'ASAHISONG.NS',
  'ASHOKA.NS', 'ASTRAMICRO.NS', 'AUTOAXLES.NS', 'AVALON.NS', 'AWL.NS',
  'BAJAJCON.NS', 'BAJAJHCARE.NS', 'BALMLAWRIE.NS', 'BANCOINDIA.NS', 'BARBEQUE.NS',
  'BCG.NS', 'BHAGCHEM.NS', 'BOMDYEING.NS', 'BORORENEW.NS', 'BRIGADE.NS',
  'CAMS.NS', 'CANTABIL.NS', 'CAPACITE.NS', 'CENTUM.NS', 'CESTAT.NS',
  'CHALET.NS', 'CHEMCON.NS', 'CHENNPETRO.NS', 'CHOICEIN.NS', 'CIGNITITEC.NS',
  'CRAFTSMAN.NS', 'CYIENTDLM.NS', 'DCBBANK.NS', 'DCMSHRIRAM.NS', 'DODLA.NS',
  'DREAMFOLKS.NS', 'DYNAMATECH.NS', 'EPL.NS', 'ETHOSLTD.NS', 'GABRIEL.NS',
  'GARFIBRES.NS', 'GATEWAY.NS', 'GENUSPOWER.NS', 'GEOJITFSL.NS', 'GHCL.NS',
  'GIPCL.NS', 'GLOBOFFS.NS', 'GOKEX.NS', 'GOLDIAM.NS', 'GREAVESCOT.NS',
  'GRSE.NS', 'GULFOILLUB.NS', 'HATHWAY.NS', 'HEIDELBERG.NS', 'HERITGFOOD.NS',
  'HIKAL.NS', 'HGS.NS', 'HMT.NS', 'HOMEFIRST.NS', 'HSCL.NS',
  'IBREALEST.NS', 'ICIL.NS', 'IDFC.NS', 'IFCI.NS', 'IIFLSEC.NS',
  'IMAGICAA.NS', 'INDIAGLYCO.NS', 'INDRAMEDCO.NS', 'INFOBEAN.NS', 'IONEXCHANG.NS',
  'IPRU.NS', 'ISGEC.NS', 'ITDC.NS', 'JAGRAN.NS', 'JAICORPLTD.NS',
  'JAMNAAUTO.NS', 'JAYNECOIND.NS', 'JINDALPOLY.NS', 'JKTYRE.NS', 'JTEKTINDIA.NS',
  'JUSTDIAL.NS', 'KDDL.NS', 'KIRLFER.NS', 'KIRLOSBROS.NS', 'KIRLOSIND.NS',
  'KOLTEPATIL.NS', 'KOPRAN.NS', 'LEMONTREE.NS', 'LUMAXTECH.NS', 'LUXIND.NS'
];

/**
 * Returns complete deduplicated 500-stock universe
 */
export function getNifty500Universe() {
  return Array.from(new Set(NIFTY_500_UNIVERSE));
}
